parameters:
    mardraze_http_host:      'http://localhost:8000'

services:
    mardraze_core.dependencies:
        class: Mardraze\CoreBundle\Service\Dependencies
        arguments: ["@service_container"]

    mardraze_core.cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: ["%kernel.cache_dir%", '.mardraze_core.cache']
